/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaApp */

#ifndef _Included_JavaApp
#define _Included_JavaApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaApp
 * Method:    writeDataReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JavaApp_writeDataReport
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JavaApp
 * Method:    readDataReport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JavaApp_readDataReport
  (JNIEnv *, jobject);
  

#ifdef __cplusplus
}
#endif
#endif
